name: CI/CD

on:
  push:
    tags:
      - v*
  pull_request:
    branches:
      - main

jobs:
  deployment:
    needs: build
    runs-on: self-hosted
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to the same server
        run: bash ${{ secrets.FAMBB_APP_DEPLOY_SCRIPT_PATH }}
